remote_theme: just-the-docs/just-the-docs
title: kamiak.org
# description: Hello world!
nav_external_links:
  - title: Battleship
    url: /battleship
    nav_order: 2
    hide_icon: true
  - title: Kamiak Chat (BETA)
    url: /chat
    nav_order: 3
    hide_icon: true
  - title: Beginner Coding Problems
    url: /problems
    nav_order: 5
    hide_icon: true